name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rust Release
        uses: manoadamro/rust-release@v1
        with:
          owner: ${{ github.repository_owner }}
          repo:  ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
